"""Constants for the Finance Tracker integration."""

DOMAIN = "finance_tracker"
PLATFORMS: list[str] = ["sensor"]
STORAGE_KEY = "storage"
SERVICES_KEY = "services"
DB_RELATIVE_PATH = "finance/tracker.db"
YAML_SENSOR_LOADED_KEY = "yaml_sensor_loaded"
WEBSOCKET_API_LOADED_KEY = "websocket_api_loaded"
FRONTEND_LOADED_KEY = "frontend_loaded"
REMINDER_MANAGER_KEY = "reminder_manager"
PANEL_FRONTEND_URL_PATH = "finance"
PANEL_TITLE = "Finance"
PANEL_ICON = "mdi:cash-multiple"
PANEL_STATIC_URL = "/finance_tracker_panel"
PANEL_ENTRYPOINT = "entrypoint.js"

SERVICE_ADD_EXPENSE = "add_expense"
SERVICE_ARCHIVE_EXPENSE = "archive_expense"
SERVICE_COPY_YEAR = "copy_year"
SERVICE_UPDATE_EXPENSE = "update_expense"
SERVICE_GENERATE_YEAR = "generate_year"
SERVICE_ACTIVATE_YEAR = "activate_year"
SERVICE_MARK_PAID = "mark_paid"
SERVICE_MARK_PARTIAL = "mark_partial"
SERVICE_UPDATE_MONTH_ENTRY = "update_month_entry"
SERVICE_UNDO_PAYMENT = "undo_payment"
SERVICE_LIST_EXPENSES = "list_expenses"
SERVICE_GET_CURRENT_MONTH = "get_current_month"
SERVICE_GET_YEAR_PLAN = "get_year_plan"
SERVICE_GET_HISTORY = "get_history"
SERVICE_GET_SETTINGS = "get_settings"
SERVICE_UPDATE_SETTINGS = "update_settings"
SERVICE_RUN_REMINDERS = "run_reminders"
SERVICE_RUN_DIAGNOSTICS = "run_diagnostics"
